all: 
	cd ./libavalam; make
	cd ./libjoueur; make
	cd ./moteur; make
	cd ./joueur; make
	
clean: 
	rm -rf ./tournoi/run/*
	cd ./libavalam; make clean
	cd ./libjoueur; make clean
	cd ./moteur; make clean
	cd ./joueur; make clean
