traiterJson({
"trait":1,
"scoreJ":24,
"scoreJ5":0,
"scoreR":22,
"scoreR5":0,
"cols":[
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":0, "couleur":0},
	{"nb":0, "couleur":0},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2},
	{"nb":1, "couleur":1},
	{"nb":1, "couleur":2}
]
});
